const products = [
  {
    id: 1,
    name: "Wireless Noise-Canceling Headphones",
    cat: "Tech",
    price: 5999,
    old: 7999,
    emoji: "🎧",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 2,
    name: "Mechanical RGB Keyboard",
    cat: "Tech",
    price: 3499,
    old: 4999,
    emoji: "⌨️",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 3,
    name: "Wireless Gaming Mouse",
    cat: "Tech",
    price: 1799,
    old: 2499,
    emoji: "🖱️",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 4,
    name: "4K Smart Monitor",
    cat: "Tech",
    price: 18999,
    old: 24999,
    emoji: "🖥️",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 5,
    name: "Portable Bluetooth Speaker",
    cat: "Tech",
    price: 2499,
    old: 3499,
    emoji: "🔊",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 6,
    name: "USB-C Hub 7-in-1",
    cat: "Tech",
    price: 1499,
    old: 2199,
    emoji: "🔌",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 7,
    name: "65W GaN Fast Charger",
    cat: "Tech",
    price: 1999,
    old: 2799,
    emoji: "🔋",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 8,
    name: "Power Bank 20000mAh",
    cat: "Tech",
    price: 1699,
    old: 2499,
    emoji: "⚡",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 9,
    name: "Smart Watch Pro",
    cat: "Tech",
    price: 5499,
    old: 7999,
    emoji: "⌚",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 10,
    name: "Fitness Band",
    cat: "Tech",
    price: 1999,
    old: 2999,
    emoji: "📱",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 11,
    name: "Webcam Full HD",
    cat: "Tech",
    price: 2299,
    old: 3299,
    emoji: "📷",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 12,
    name: "Laptop Stand",
    cat: "Tech",
    price: 999,
    old: 1599,
    emoji: "💻",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 13,
    name: "Tablet 10-inch",
    cat: "Tech",
    price: 12999,
    old: 16999,
    emoji: "📱",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 14,
    name: "Mini Projector",
    cat: "Tech",
    price: 6999,
    old: 9999,
    emoji: "📽️",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 15,
    name: "Wi-Fi 6 Router",
    cat: "Tech",
    price: 3999,
    old: 5499,
    emoji: "📡",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 16,
    name: "Portable SSD 1TB",
    cat: "Tech",
    price: 7499,
    old: 9999,
    emoji: "💾",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 17,
    name: "MicroSD Card 256GB",
    cat: "Tech",
    price: 1299,
    old: 1899,
    emoji: "💳",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 18,
    name: "Smart LED Bulb",
    cat: "Tech",
    price: 599,
    old: 999,
    emoji: "💡",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 19,
    name: "Smart Plug",
    cat: "Tech",
    price: 799,
    old: 1199,
    emoji: "🔌",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 20,
    name: "Bluetooth Earbuds",
    cat: "Tech",
    price: 2299,
    old: 3499,
    emoji: "🎶",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 21,
    name: "Gaming Headset",
    cat: "Tech",
    price: 2999,
    old: 4499,
    emoji: "🎮",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 22,
    name: "Game Controller",
    cat: "Tech",
    price: 2499,
    old: 3499,
    emoji: "🕹️",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 23,
    name: "Laptop Cooling Pad",
    cat: "Tech",
    price: 1299,
    old: 1899,
    emoji: "❄️",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 24,
    name: "Phone Gimbal",
    cat: "Tech",
    price: 4499,
    old: 6499,
    emoji: "📹",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 25,
    name: "Wireless Charging Pad",
    cat: "Tech",
    price: 999,
    old: 1499,
    emoji: "🔋",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 26,
    name: "USB Desk Fan",
    cat: "Tech",
    price: 699,
    old: 999,
    emoji: "🌀",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 27,
    name: "Cable Organizer",
    cat: "Tech",
    price: 399,
    old: 699,
    emoji: "🧵",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 28,
    name: "Smart Doorbell",
    cat: "Tech",
    price: 4999,
    old: 6999,
    emoji: "🔔",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 29,
    name: "Action Camera",
    cat: "Tech",
    price: 8999,
    old: 12999,
    emoji: "📸",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 30,
    name: "E-Reader",
    cat: "Tech",
    price: 10999,
    old: 14999,
    emoji: "📖",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 31,
    name: "Smart Speaker",
    cat: "Tech",
    price: 2999,
    old: 4499,
    emoji: "🔈",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 32,
    name: "VR Headset",
    cat: "Tech",
    price: 24999,
    old: 32999,
    emoji: "🥽",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 33,
    name: "Drawing Tablet",
    cat: "Tech",
    price: 4999,
    old: 6999,
    emoji: "✍️",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 34,
    name: "Laser Printer",
    cat: "Tech",
    price: 8999,
    old: 11999,
    emoji: "🖨️",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 35,
    name: "Bluetooth Keyboard",
    cat: "Tech",
    price: 1299,
    old: 1999,
    emoji: "⌨️",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 36,
    name: "Ergonomic Mouse",
    cat: "Tech",
    price: 999,
    old: 1499,
    emoji: "🖱️",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 37,
    name: "Laptop Backpack Tech",
    cat: "Tech",
    price: 1999,
    old: 2999,
    emoji: "🎒",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 38,
    name: "Cable Fast-Charging Kit",
    cat: "Tech",
    price: 799,
    old: 1199,
    emoji: "🔗",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 39,
    name: "Smart Scale",
    cat: "Tech",
    price: 1499,
    old: 2299,
    emoji: "⚖️",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 40,
    name: "Digital Alarm Clock",
    cat: "Tech",
    price: 899,
    old: 1299,
    emoji: "⏰",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 41,
    name: "Mini Power Station",
    cat: "Tech",
    price: 12999,
    old: 17999,
    emoji: "🔌",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 42,
    name: "LED Monitor Light",
    cat: "Tech",
    price: 1799,
    old: 2499,
    emoji: "💡",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 43,
    name: "USB Microphone",
    cat: "Tech",
    price: 2999,
    old: 4499,
    emoji: "🎙️",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 44,
    name: "Smart Tracker Tag",
    cat: "Tech",
    price: 999,
    old: 1499,
    emoji: "📍",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 45,
    name: "Bluetooth Adapter",
    cat: "Tech",
    price: 499,
    old: 799,
    emoji: "📶",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 46,
    name: "External DVD Drive",
    cat: "Tech",
    price: 1299,
    old: 1899,
    emoji: "💿",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 47,
    name: "NFC Card Reader",
    cat: "Tech",
    price: 1599,
    old: 2299,
    emoji: "💳",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 48,
    name: "Smart Home Camera",
    cat: "Tech",
    price: 2999,
    old: 4499,
    emoji: "📹",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 49,
    name: "Phone Tripod",
    cat: "Tech",
    price: 899,
    old: 1399,
    emoji: "📱",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 50,
    name: "Portable Wi-Fi Hotspot",
    cat: "Tech",
    price: 3499,
    old: 4999,
    emoji: "📡",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 51,
    name: "Minimal Desk Lamp",
    cat: "Home",
    price: 1299,
    old: 1899,
    emoji: "💡",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 52,
    name: "Memory Foam Pillow",
    cat: "Home",
    price: 899,
    old: 1399,
    emoji: "🛏️",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 53,
    name: "Cotton Bedsheet Set",
    cat: "Home",
    price: 1499,
    old: 2299,
    emoji: "🛌",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 54,
    name: "Weighted Blanket",
    cat: "Home",
    price: 2499,
    old: 3499,
    emoji: "🧺",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 55,
    name: "Ceramic Vase",
    cat: "Home",
    price: 799,
    old: 1199,
    emoji: "🏺",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 56,
    name: "Wall Clock",
    cat: "Home",
    price: 999,
    old: 1499,
    emoji: "🕐",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 57,
    name: "Scented Candle Set",
    cat: "Home",
    price: 699,
    old: 999,
    emoji: "🕯️",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 58,
    name: "Aroma Diffuser",
    cat: "Home",
    price: 1599,
    old: 2299,
    emoji: "🌫️",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 59,
    name: "Indoor Plant Pot",
    cat: "Home",
    price: 499,
    old: 799,
    emoji: "🪴",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 60,
    name: "Artificial Plant",
    cat: "Home",
    price: 899,
    old: 1399,
    emoji: "🌿",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 61,
    name: "Storage Basket",
    cat: "Home",
    price: 699,
    old: 1099,
    emoji: "🧺",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 62,
    name: "Laundry Organizer",
    cat: "Home",
    price: 999,
    old: 1499,
    emoji: "🧴",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 63,
    name: "Kitchen Knife Set",
    cat: "Home",
    price: 1499,
    old: 2199,
    emoji: "🔪",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 64,
    name: "Non-Stick Pan",
    cat: "Home",
    price: 1299,
    old: 1899,
    emoji: "🍳",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 65,
    name: "Dinner Set",
    cat: "Home",
    price: 2499,
    old: 3499,
    emoji: "🍽️",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 66,
    name: "Coffee Mug Set",
    cat: "Home",
    price: 699,
    old: 999,
    emoji: "☕",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 67,
    name: "Electric Kettle",
    cat: "Home",
    price: 1799,
    old: 2499,
    emoji: "🫖",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 68,
    name: "French Press",
    cat: "Home",
    price: 999,
    old: 1499,
    emoji: "☕",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 69,
    name: "Air Fryer",
    cat: "Home",
    price: 4999,
    old: 6999,
    emoji: "🍟",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 70,
    name: "Mixer Grinder",
    cat: "Home",
    price: 3499,
    old: 4999,
    emoji: "🥣",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 71,
    name: "Toaster",
    cat: "Home",
    price: 1799,
    old: 2499,
    emoji: "🍞",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 72,
    name: "Rice Cooker",
    cat: "Home",
    price: 2499,
    old: 3499,
    emoji: "🍚",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 73,
    name: "Water Bottle",
    cat: "Home",
    price: 699,
    old: 999,
    emoji: "🚰",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 74,
    name: "Glass Storage Set",
    cat: "Home",
    price: 999,
    old: 1499,
    emoji: "🥫",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 75,
    name: "Spice Rack",
    cat: "Home",
    price: 799,
    old: 1199,
    emoji: "🧂",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 76,
    name: "Cutting Board",
    cat: "Home",
    price: 499,
    old: 799,
    emoji: "🔪",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 77,
    name: "Kitchen Scale",
    cat: "Home",
    price: 799,
    old: 1199,
    emoji: "⚖️",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 78,
    name: "Dish Rack",
    cat: "Home",
    price: 899,
    old: 1399,
    emoji: "🍽️",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 79,
    name: "Bathroom Organizer",
    cat: "Home",
    price: 599,
    old: 899,
    emoji: "🧼",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 80,
    name: "Shower Caddy",
    cat: "Home",
    price: 799,
    old: 1199,
    emoji: "🚿",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 81,
    name: "Bath Towel Set",
    cat: "Home",
    price: 1299,
    old: 1999,
    emoji: "🛁",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 82,
    name: "Floor Mat",
    cat: "Home",
    price: 599,
    old: 999,
    emoji: "🧹",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 83,
    name: "Vacuum Cleaner",
    cat: "Home",
    price: 6999,
    old: 9999,
    emoji: "🧹",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 84,
    name: "Handheld Vacuum",
    cat: "Home",
    price: 2499,
    old: 3499,
    emoji: "🧽",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 85,
    name: "Steam Iron",
    cat: "Home",
    price: 1999,
    old: 2999,
    emoji: "👔",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 86,
    name: "Clothes Hanger Set",
    cat: "Home",
    price: 399,
    old: 699,
    emoji: "👕",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 87,
    name: "Sofa Cushion Set",
    cat: "Home",
    price: 899,
    old: 1399,
    emoji: "🛋️",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 88,
    name: "Throw Blanket",
    cat: "Home",
    price: 1199,
    old: 1799,
    emoji: "🧣",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 89,
    name: "Curtain Set",
    cat: "Home",
    price: 1499,
    old: 2299,
    emoji: "🪟",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 90,
    name: "Table Runner",
    cat: "Home",
    price: 599,
    old: 899,
    emoji: "🧵",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 91,
    name: "Decorative Mirror",
    cat: "Home",
    price: 1999,
    old: 2999,
    emoji: "🪞",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 92,
    name: "Photo Frame Set",
    cat: "Home",
    price: 799,
    old: 1199,
    emoji: "🖼️",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 93,
    name: "LED Strip Lights",
    cat: "Home",
    price: 699,
    old: 1099,
    emoji: "🌈",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 94,
    name: "Night Light",
    cat: "Home",
    price: 499,
    old: 799,
    emoji: "🌙",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 95,
    name: "Humidifier",
    cat: "Home",
    price: 1899,
    old: 2799,
    emoji: "💧",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 96,
    name: "Air Purifier",
    cat: "Home",
    price: 6999,
    old: 9999,
    emoji: "🌬️",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 97,
    name: "Robot Vacuum",
    cat: "Home",
    price: 22999,
    old: 29999,
    emoji: "🤖",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 98,
    name: "Laundry Hamper",
    cat: "Home",
    price: 999,
    old: 1499,
    emoji: "🧺",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 99,
    name: "Door Mat",
    cat: "Home",
    price: 499,
    old: 799,
    emoji: "🚪",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 100,
    name: "Bookshelf",
    cat: "Home",
    price: 2999,
    old: 4499,
    emoji: "📚",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 101,
    name: "Minimal Runner Sneakers",
    cat: "Fashion",
    price: 2999,
    old: 4499,
    emoji: "👟",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 102,
    name: "Classic Oversized Tee",
    cat: "Fashion",
    price: 999,
    old: 1499,
    emoji: "👕",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 103,
    name: "Slim Fit Jeans",
    cat: "Fashion",
    price: 1999,
    old: 2999,
    emoji: "👖",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 104,
    name: "Denim Jacket",
    cat: "Fashion",
    price: 2499,
    old: 3499,
    emoji: "🧥",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 105,
    name: "Casual Hoodie",
    cat: "Fashion",
    price: 1799,
    old: 2699,
    emoji: "🧥",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 106,
    name: "Cotton Shirt",
    cat: "Fashion",
    price: 1299,
    old: 1999,
    emoji: "👔",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 107,
    name: "Polo T-Shirt",
    cat: "Fashion",
    price: 999,
    old: 1499,
    emoji: "👕",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 108,
    name: "Cargo Pants",
    cat: "Fashion",
    price: 1899,
    old: 2799,
    emoji: "👖",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 109,
    name: "Chino Pants",
    cat: "Fashion",
    price: 1699,
    old: 2499,
    emoji: "👖",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 110,
    name: "Bomber Jacket",
    cat: "Fashion",
    price: 2999,
    old: 4499,
    emoji: "🧥",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 111,
    name: "Formal Blazer",
    cat: "Fashion",
    price: 3999,
    old: 5999,
    emoji: "🤵",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 112,
    name: "Formal Trousers",
    cat: "Fashion",
    price: 1999,
    old: 2999,
    emoji: "👖",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 113,
    name: "Kurta Set",
    cat: "Fashion",
    price: 1799,
    old: 2699,
    emoji: "🥻",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 114,
    name: "Casual Kurta",
    cat: "Fashion",
    price: 1199,
    old: 1799,
    emoji: "👕",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 115,
    name: "Ethnic Jacket",
    cat: "Fashion",
    price: 2499,
    old: 3499,
    emoji: "🧥",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 116,
    name: "Saree Collection",
    cat: "Fashion",
    price: 2499,
    old: 3999,
    emoji: "🥻",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 117,
    name: "Anarkali Dress",
    cat: "Fashion",
    price: 2299,
    old: 3499,
    emoji: "👗",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 118,
    name: "Maxi Dress",
    cat: "Fashion",
    price: 1999,
    old: 2999,
    emoji: "👗",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 119,
    name: "Summer Dress",
    cat: "Fashion",
    price: 1499,
    old: 2299,
    emoji: "👗",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 120,
    name: "Bodycon Dress",
    cat: "Fashion",
    price: 1799,
    old: 2699,
    emoji: "👗",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 121,
    name: "Crop Top",
    cat: "Fashion",
    price: 699,
    old: 999,
    emoji: "👚",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 122,
    name: "Women Hoodie",
    cat: "Fashion",
    price: 1599,
    old: 2399,
    emoji: "🧥",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 123,
    name: "Women Jeans",
    cat: "Fashion",
    price: 1899,
    old: 2799,
    emoji: "👖",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 124,
    name: "Wide Leg Pants",
    cat: "Fashion",
    price: 1699,
    old: 2499,
    emoji: "👖",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 125,
    name: "Running Shoes",
    cat: "Fashion",
    price: 2799,
    old: 3999,
    emoji: "👟",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 126,
    name: "Casual Sneakers",
    cat: "Fashion",
    price: 2399,
    old: 3499,
    emoji: "👟",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 127,
    name: "Leather Loafers",
    cat: "Fashion",
    price: 2499,
    old: 3799,
    emoji: "👞",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 128,
    name: "Sports Sandals",
    cat: "Fashion",
    price: 1199,
    old: 1799,
    emoji: "🩴",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 129,
    name: "Flip Flops",
    cat: "Fashion",
    price: 499,
    old: 799,
    emoji: "🩴",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 130,
    name: "Leather Belt",
    cat: "Fashion",
    price: 699,
    old: 1099,
    emoji: "🪢",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 131,
    name: "Classic Wallet",
    cat: "Fashion",
    price: 899,
    old: 1399,
    emoji: "👛",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 132,
    name: "Leather Handbag",
    cat: "Fashion",
    price: 2499,
    old: 3999,
    emoji: "👜",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 133,
    name: "Sling Bag",
    cat: "Fashion",
    price: 1299,
    old: 1999,
    emoji: "👜",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 134,
    name: "Travel Backpack",
    cat: "Fashion",
    price: 1799,
    old: 2699,
    emoji: "🎒",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 135,
    name: "Baseball Cap",
    cat: "Fashion",
    price: 499,
    old: 799,
    emoji: "🧢",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 136,
    name: "Winter Beanie",
    cat: "Fashion",
    price: 399,
    old: 699,
    emoji: "🧢",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 137,
    name: "Sunglasses",
    cat: "Fashion",
    price: 999,
    old: 1599,
    emoji: "🕶️",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 138,
    name: "Analog Watch",
    cat: "Fashion",
    price: 2499,
    old: 3999,
    emoji: "⌚",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 139,
    name: "Minimal Bracelet",
    cat: "Fashion",
    price: 599,
    old: 999,
    emoji: "📿",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 140,
    name: "Chain Necklace",
    cat: "Fashion",
    price: 799,
    old: 1299,
    emoji: "📿",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 141,
    name: "Stud Earrings",
    cat: "Fashion",
    price: 499,
    old: 899,
    emoji: "💎",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 142,
    name: "Hoop Earrings",
    cat: "Fashion",
    price: 699,
    old: 1099,
    emoji: "💎",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 143,
    name: "Silk Scarf",
    cat: "Fashion",
    price: 599,
    old: 999,
    emoji: "🧣",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 144,
    name: "Winter Gloves",
    cat: "Fashion",
    price: 699,
    old: 999,
    emoji: "🧤",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 145,
    name: "Wool Sweater",
    cat: "Fashion",
    price: 1999,
    old: 2999,
    emoji: "🧶",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 146,
    name: "Puffer Jacket",
    cat: "Fashion",
    price: 3499,
    old: 4999,
    emoji: "🧥",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 147,
    name: "Sports Shorts",
    cat: "Fashion",
    price: 899,
    old: 1299,
    emoji: "🩳",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 148,
    name: "Gym Track Pants",
    cat: "Fashion",
    price: 1299,
    old: 1899,
    emoji: "👖",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 149,
    name: "Activewear Set",
    cat: "Fashion",
    price: 1999,
    old: 2999,
    emoji: "🏃",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 150,
    name: "Rain Jacket",
    cat: "Fashion",
    price: 1899,
    old: 2799,
    emoji: "🌧️",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 151,
    name: "Aura Skincare Set",
    cat: "Beauty",
    price: 1599,
    old: 2199,
    emoji: "🧴",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 152,
    name: "Vitamin C Serum",
    cat: "Beauty",
    price: 799,
    old: 1199,
    emoji: "✨",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 153,
    name: "Hydrating Face Wash",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🫧",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 154,
    name: "Moisturizing Cream",
    cat: "Beauty",
    price: 699,
    old: 999,
    emoji: "🧴",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 155,
    name: "Sunscreen SPF 50",
    cat: "Beauty",
    price: 799,
    old: 1199,
    emoji: "☀️",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 156,
    name: "Niacinamide Serum",
    cat: "Beauty",
    price: 699,
    old: 999,
    emoji: "💧",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 157,
    name: "Hyaluronic Acid Serum",
    cat: "Beauty",
    price: 899,
    old: 1299,
    emoji: "💦",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 158,
    name: "Retinol Night Cream",
    cat: "Beauty",
    price: 999,
    old: 1499,
    emoji: "🌙",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 159,
    name: "Aloe Vera Gel",
    cat: "Beauty",
    price: 399,
    old: 599,
    emoji: "🌿",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 160,
    name: "Clay Face Mask",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🧖",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 161,
    name: "Sheet Mask Pack",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "🎭",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 162,
    name: "Lip Balm Set",
    cat: "Beauty",
    price: 399,
    old: 699,
    emoji: "💄",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 163,
    name: "Matte Lipstick",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "💄",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 164,
    name: "Lip Gloss",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "💋",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 165,
    name: "Liquid Foundation",
    cat: "Beauty",
    price: 899,
    old: 1299,
    emoji: "💄",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 166,
    name: "Concealer",
    cat: "Beauty",
    price: 699,
    old: 999,
    emoji: "✨",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 167,
    name: "Compact Powder",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "🪞",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 168,
    name: "Blush Palette",
    cat: "Beauty",
    price: 799,
    old: 1199,
    emoji: "🌸",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 169,
    name: "Eyeshadow Palette",
    cat: "Beauty",
    price: 999,
    old: 1499,
    emoji: "🎨",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 170,
    name: "Mascara",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "👁️",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 171,
    name: "Eyeliner",
    cat: "Beauty",
    price: 399,
    old: 699,
    emoji: "🖊️",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 172,
    name: "Makeup Brush Set",
    cat: "Beauty",
    price: 799,
    old: 1299,
    emoji: "🖌️",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 173,
    name: "Beauty Blender Set",
    cat: "Beauty",
    price: 399,
    old: 699,
    emoji: "🧽",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 174,
    name: "Makeup Remover",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🫧",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 175,
    name: "Micellar Water",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "💧",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 176,
    name: "Hair Shampoo",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🧴",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 177,
    name: "Hair Conditioner",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🧴",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 178,
    name: "Hair Serum",
    cat: "Beauty",
    price: 699,
    old: 999,
    emoji: "✨",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 179,
    name: "Hair Mask",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "🧖",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 180,
    name: "Hair Oil",
    cat: "Beauty",
    price: 399,
    old: 699,
    emoji: "🌿",
    rating: "4.9",
    badge: "POPULAR",
  },
  {
    id: 181,
    name: "Body Lotion",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🧴",
    rating: "4.5",
    badge: "SALE",
  },
  {
    id: 182,
    name: "Body Scrub",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "🫧",
    rating: "4.6",
    badge: "BESTSELLER",
  },
  {
    id: 183,
    name: "Body Wash",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🚿",
    rating: "4.7",
    badge: "NEW",
  },
  {
    id: 184,
    name: "Bath Salt",
    cat: "Beauty",
    price: 599,
    old: 899,
    emoji: "🛁",
    rating: "4.8",
    badge: "POPULAR",
  },
  {
    id: 185,
    name: "Perfume for Men",
    cat: "Beauty",
    price: 1499,
    old: 2499,
    emoji: "🌿",
    rating: "4.9",
    badge: "SALE",
  },
  {
    id: 186,
    name: "Perfume for Women",
    cat: "Beauty",
    price: 1699,
    old: 2799,
    emoji: "🌸",
    rating: "4.5",
    badge: "BESTSELLER",
  },
  {
    id: 187,
    name: "Deodorant Spray",
    cat: "Beauty",
    price: 399,
    old: 699,
    emoji: "🌬️",
    rating: "4.6",
    badge: "NEW",
  },
  {
    id: 188,
    name: "Essential Oil Set",
    cat: "Beauty",
    price: 799,
    old: 1199,
    emoji: "🌿",
    rating: "4.7",
    badge: "POPULAR",
  },
  {
    id: 189,
    name: "Nail Polish Set",
    cat: "Beauty",
    price: 599,
    old: 999,
    emoji: "💅",
    rating: "4.8",
    badge: "SALE",
  },
  {
    id: 190,
    name: "Nail Care Kit",
    cat: "Beauty",
    price: 699,
    old: 1099,
    emoji: "💅",
    rating: "4.9",
    badge: "BESTSELLER",
  },
  {
    id: 191,
    name: "Face Roller",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🪨",
    rating: "4.5",
    badge: "NEW",
  },
  {
    id: 192,
    name: "Gua Sha",
    cat: "Beauty",
    price: 399,
    old: 699,
    emoji: "🪨",
    rating: "4.6",
    badge: "POPULAR",
  },
  {
    id: 193,
    name: "Electric Facial Cleanser",
    cat: "Beauty",
    price: 1299,
    old: 1899,
    emoji: "🧖",
    rating: "4.7",
    badge: "SALE",
  },
  {
    id: 194,
    name: "Hair Straightener",
    cat: "Beauty",
    price: 1999,
    old: 2999,
    emoji: "💇",
    rating: "4.8",
    badge: "BESTSELLER",
  },
  {
    id: 195,
    name: "Hair Dryer",
    cat: "Beauty",
    price: 1799,
    old: 2699,
    emoji: "💨",
    rating: "4.9",
    badge: "NEW",
  },
  {
    id: 196,
    name: "Curling Wand",
    cat: "Beauty",
    price: 1699,
    old: 2499,
    emoji: "💇",
    rating: "4.5",
    badge: "POPULAR",
  },
  {
    id: 197,
    name: "Beard Trimmer",
    cat: "Beauty",
    price: 1999,
    old: 2999,
    emoji: "🧔",
    rating: "4.6",
    badge: "SALE",
  },
  {
    id: 198,
    name: "Beard Oil",
    cat: "Beauty",
    price: 499,
    old: 799,
    emoji: "🧴",
    rating: "4.7",
    badge: "BESTSELLER",
  },
  {
    id: 199,
    name: "Men Grooming Kit",
    cat: "Beauty",
    price: 1499,
    old: 2299,
    emoji: "🧔",
    rating: "4.8",
    badge: "NEW",
  },
  {
    id: 200,
    name: "Beauty Travel Kit",
    cat: "Beauty",
    price: 999,
    old: 1499,
    emoji: "🧳",
    rating: "4.9",
    badge: "POPULAR",
  },
];

let activeFilter = "All";
let cart = JSON.parse(localStorage.getItem("novacart") || "[]");

const productGrid = document.getElementById("productGrid");
const cartDrawer = document.getElementById("cartDrawer");
const overlay = document.getElementById("overlay");
const cartItems = document.getElementById("cartItems");
const cartCount = document.getElementById("cartCount");
const cartTotal = document.getElementById("cartTotal");
const toast = document.getElementById("toast");

function money(n) {
  return "₹" + n.toLocaleString("en-IN");
}

function renderProducts() {
  const filtered =
    activeFilter === "All"
      ? products
      : products.filter((p) => p.cat === activeFilter);
  productGrid.innerHTML = filtered
    .map(
      (p, i) => `
    <article class="product reveal" style="transition-delay:${(i % 12) * 25}ms">
      <div class="product-img">
        <span class="badge">${p.badge}</span>
        <button class="heart" onclick="this.textContent=this.textContent==='♡'?'♥':'♡'">♡</button>
        <span>${p.emoji}</span>
      </div>
      <div class="product-info">
        <span class="category-name">${p.cat}</span>
        <h3>${p.name}</h3>
        <div class="rating">★★★★★ <span>${p.rating}</span></div>
        <div class="price-row">
          <div><span class="price">${money(p.price)}</span> <del style="color:#aaa;font-size:10px">${money(p.old)}</del></div>
          <button class="add" onclick="addToCart(${p.id})">+</button>
        </div>
      </div>
    </article>`,
    )
    .join("");
  setTimeout(observeReveals, 20);
}

function addToCart(id) {
  const found = cart.find((x) => x.id === id);
  if (found) found.qty++;
  else cart.push({ id, qty: 1 });
  saveCart();
  showToast("Added to your cart ✨");
  openCart();
}
function saveCart() {
  localStorage.setItem("novacart", JSON.stringify(cart));
  renderCart();
}
function renderCart() {
  let total = 0,
    count = 0;
  cartItems.innerHTML = cart.length
    ? cart
        .map((item) => {
          const p = products.find((x) => x.id === item.id);
          if (!p) return "";
          total += p.price * item.qty;
          count += item.qty;
          return `<div class="cart-item"><div class="mini-img">${p.emoji}</div><div class="cart-item-info"><h4>${p.name}</h4><p>${money(p.price)}</p><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${item.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div></div><button onclick="removeItem(${p.id})" style="background:none;color:#aaa">×</button></div>`;
        })
        .join("")
    : `<div style="text-align:center;color:#999;padding:70px 20px">Your cart is empty.<br><br>Start shopping to add products.</div>`;
  cartCount.textContent = count;
  cartTotal.textContent = money(total);
}
function changeQty(id, delta) {
  const item = cart.find((x) => x.id === id);
  if (!item) return;
  item.qty += delta;
  if (item.qty <= 0) cart = cart.filter((x) => x.id !== id);
  saveCart();
}
function removeItem(id) {
  cart = cart.filter((x) => x.id !== id);
  saveCart();
}
function openCart() {
  cartDrawer.classList.add("open");
  overlay.classList.add("show");
  document.body.classList.add("lock");
}
function closeCart() {
  cartDrawer.classList.remove("open");
  overlay.classList.remove("show");
  document.body.classList.remove("lock");
}
document.getElementById("cartBtn").onclick = openCart;
document.getElementById("closeCart").onclick = closeCart;
overlay.onclick = closeCart;

document.querySelectorAll(".filter,.category").forEach((btn) => {
  btn.addEventListener("click", () => {
    activeFilter = btn.dataset.filter;
    document
      .querySelectorAll(".filter")
      .forEach((x) =>
        x.classList.toggle("active", x.dataset.filter === activeFilter),
      );
    document.getElementById("shop").scrollIntoView({ behavior: "smooth" });
    renderProducts();
  });
});

document.getElementById("searchBtn").onclick = () =>
  document.getElementById("searchPanel").classList.toggle("show");
document.getElementById("searchInput").addEventListener("input", (e) => {
  const q = e.target.value.toLowerCase();
  const result = products.filter((p) =>
    (p.name + " " + p.cat).toLowerCase().includes(q),
  );
  productGrid.innerHTML =
    result
      .map(
        (p, i) => `
  <article class="product reveal visible" style="transition-delay:${(i % 12) * 25}ms">
    <div class="product-img"><span class="badge">${p.badge}</span><button class="heart" onclick="this.textContent=this.textContent==='♡'?'♥':'♡'">♡</button><span>${p.emoji}</span></div>
    <div class="product-info"><span class="category-name">${p.cat}</span><h3>${p.name}</h3><div class="rating">★★★★★ <span>${p.rating}</span></div><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" onclick="addToCart(${p.id})">+</button></div></div>
  </article>`,
      )
      .join("") || `<p style="color:#888">No products found.</p>`;
});

document.getElementById("menuBtn").onclick = () => {
  const nav = document.querySelector("nav");
  nav.style.display = nav.style.display === "flex" ? "none" : "flex";
  nav.style.position = "absolute";
  nav.style.top = "76px";
  nav.style.left = "0";
  nav.style.right = "0";
  nav.style.padding = "20px";
  nav.style.background = "#fff";
  nav.style.flexDirection = "column";
  nav.style.gap = "18px";
};
document.getElementById("newsletterForm").addEventListener("submit", (e) => {
  e.preventDefault();
  e.target.reset();
  showToast("You're subscribed! Welcome to NovaCart 🎉");
});
document.getElementById("checkout").onclick = () => {
  if (!cart.length) {
    showToast("Your cart is empty");
    return;
  }
  cart = [];
  saveCart();
  closeCart();
  showToast("Order placed successfully! 🎉");
};
function showToast(msg) {
  toast.textContent = msg;
  toast.classList.add("show");
  clearTimeout(window.toastTimer);
  window.toastTimer = setTimeout(() => toast.classList.remove("show"), 2400);
}
function observeReveals() {
  const io = new IntersectionObserver(
    (entries) =>
      entries.forEach((e) => {
        if (e.isIntersecting) e.target.classList.add("visible");
      }),
    { threshold: 0.08 },
  );
  document
    .querySelectorAll(".reveal:not(.visible)")
    .forEach((el) => io.observe(el));
}
function startCountdown() {
  let end = Date.now() + 2 * 86400000 + 12 * 3600000 + 34 * 60000 + 56000;
  function tick() {
    let d = Math.max(0, end - Date.now());
    let vals = [
      Math.floor(d / 86400000),
      Math.floor(d / 3600000) % 24,
      Math.floor(d / 60000) % 60,
      Math.floor(d / 1000) % 60,
    ];
    ["days", "hours", "minutes", "seconds"].forEach(
      (id, i) =>
        (document.getElementById(id).textContent = String(vals[i]).padStart(
          2,
          "0",
        )),
    );
  }
  tick();
  setInterval(tick, 1000);
}
window.addEventListener("load", () => {
  setTimeout(
    () => (document.querySelector(".loader").style.opacity = "0"),
    700,
  );
  setTimeout(() => document.querySelector(".loader").remove(), 1300);
  renderProducts();
  renderCart();
  observeReveals();
  startCountdown();
});
